# Generated by Django 5.1.6 on 2025-03-13 11:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_price_remove_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload an image of the property', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(help_text='Upload a video of the property (max 1 video per property)', max_length=255, verbose_name='video'),
        ),
    ]
