# Generated by Django 5.1.6 on 2025-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyimage_image_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities available with this property'),
        ),
    ]
