# Generated by Django 5.1.6 on 2025-03-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or code', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Amenities available with this property', related_name='properties', to='properties.amenity'),
        ),
    ]
