# Generated by Django 5.1.6 on 2025-03-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_amenity_remove_property_amenities_property_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-listed_date'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
