# Generated by Django 5.1.6 on 2025-03-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
    ]
