# Generated by Django 5.1.6 on 2025-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_agent_commission_property_lister_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the property has been verified by admin'),
        ),
    ]
