# Generated by Django 5.1.6 on 2025-06-01 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listed_by',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['ADMIN', 'AGENT', 'LANDLORD']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
