# Generated by Django 5.1.6 on 2025-06-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_propertyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='City where the property is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, help_text='State where the property is located', max_length=100, null=True),
        ),
    ]
