# Generated by Django 5.1.6 on 2025-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_property_lister_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_commission',
            field=models.FloatField(blank=True, help_text='Agent commission percentage', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='qaba_fee',
            field=models.FloatField(blank=True, help_text='Qaba fee percentage', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.FloatField(blank=True, help_text='Rent price (applicable for rental listings)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.FloatField(blank=True, help_text='Sale price', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_price',
            field=models.FloatField(blank=True, help_text='Total price', null=True),
        ),
    ]
