# Generated by Django 4.2.15 on 2025-10-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_alter_property_agent_commission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="caution_fee",
            field=models.FloatField(
                blank=True,
                help_text="Optional caution fee required for the property",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="service_charge",
            field=models.FloatField(
                blank=True,
                help_text="Optional service charge applied to the property",
                null=True,
            ),
        ),
    ]
