# Generated by Django 4.2.15 on 2025-10-18 23:22

from django.db import migrations, models


def cleanup_orphan_user_relations(apps, schema_editor):
    User = apps.get_model("users", "User")
    valid_user_ids = set(User.objects.values_list("id", flat=True))

    def handle_orphans(app_label, model_name, field_name, nullable=False):
        Model = apps.get_model(app_label, model_name)

        if not Model.objects.exists():
            return

        if valid_user_ids:
            filter_kwargs = {f"{field_name}__in": valid_user_ids}
            orphans = Model.objects.exclude(**filter_kwargs)
        else:
            orphans = Model.objects.all()

        if not orphans.exists():
            return

        if nullable:
            target_field = field_name[:-3] if field_name.endswith("_id") else field_name
            update_kwargs = {target_field: None}
            orphans.update(**update_kwargs)
        else:
            orphans.delete()

    relations_to_cleanup = [
        ("users", "OTP", "user_id", False),
        ("users", "ClientProfile", "user_id", False),
        ("users", "AgentProfile", "user_id", False),
        ("users", "LandlordProfile", "user_id", False),
        ("users", "Notification", "user_id", False),
        ("users", "PropertySurveyMeeting", "user_id", False),
        ("properties", "Property", "listed_by_id", False),
        ("properties", "Favorite", "user_id", False),
        ("properties", "PropertyDocument", "uploaded_by_id", True),
        ("properties", "PropertyReview", "reviewer_id", False),
        ("properties", "PropertyReview", "approved_by_id", True),
        ("transactions", "Transaction", "user_id", False),
        ("transactions", "Transaction", "verified_by_id", True),
    ]

    for app_label, model_name, field_name, nullable in relations_to_cleanup:
        handle_orphans(app_label, model_name, field_name, nullable)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_alter_property_agent_commission_and_more"),
        ("users", "0012_remove_user_email_verification_token_otp"),  # OTP model dependency
        ("transactions", "0001_initial"),  # Transaction model dependency
    ]

    operations = [
        migrations.RunPython(cleanup_orphan_user_relations, migrations.RunPython.noop),
        migrations.AddField(
            model_name="property",
            name="caution_fee",
            field=models.FloatField(
                blank=True,
                help_text="Optional caution fee required for the property",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="service_charge",
            field=models.FloatField(
                blank=True,
                help_text="Optional service charge applied to the property",
                null=True,
            ),
        ),
    ]
