# Generated by Django 4.2.15 on 2025-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0022_property_caution_fee_property_service_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="legal_fee",
            field=models.FloatField(
                blank=True,
                help_text="Optional legal fee applied to the property",
                null=True,
            ),
        ),
    ]
