# Generated by Django 4.2.15 on 2025-10-24 14:32

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Property = apps.get_model("properties", "Property")

    for property_obj in Property.objects.all():
        base_slug = slugify(property_obj.property_name) or "property"
        slug = base_slug
        counter = 1

        while (
            Property.objects.exclude(pk=property_obj.pk).filter(slug=slug).exists()
        ):
            slug = f"{base_slug}-{counter}"
            counter += 1

        property_obj.slug = slug
        property_obj.save(update_fields=["slug"])


def remove_slug(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    Property.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0023_property_legal_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            code=populate_slug,
            reverse_code=remove_slug,
        ),
    ]
