# Generated by Django 4.2.15 on 2025-10-24 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_property_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
