# Generated by Django 4.2.15 on 2025-10-24

from django.db import migrations


class Migration(migrations.Migration):
    """
    Placeholder migration to supersede the previous UUID primary-key attempt.
    Keeps the schema unchanged so existing bigint IDs remain intact.
    """

    dependencies = [
        ("properties", "0024_property_slug"),
    ]

    operations = []
