# Generated by Django 4.2.15 on 2025-11-16 02:21

import uuid
import re
from django.db import migrations


def generate_property_ids(apps, schema_editor):
    """Generate property_id for all existing properties"""
    Property = apps.get_model("properties", "Property")

    for property_obj in Property.objects.filter(property_id=""):
        # Generate property_id inline (can't call model's save method in migrations)
        # Get first 2-3 words from property name, clean and uppercase
        name_parts = property_obj.property_name.upper().split()[:3]
        name_prefix = "-".join(name_parts)

        # Remove special characters and limit length
        name_prefix = re.sub(r'[^A-Z0-9-]', '', name_prefix)
        name_prefix = name_prefix[:30]

        # Generate unique code using short UUID
        unique_code = str(uuid.uuid4()).split('-')[0].upper()

        property_id = f"PROP-{name_prefix}-{unique_code}"

        # Ensure uniqueness
        while Property.objects.filter(property_id=property_id).exists():
            unique_code = str(uuid.uuid4()).split('-')[0].upper()
            property_id = f"PROP-{name_prefix}-{unique_code}"

        property_obj.property_id = property_id
        property_obj.save(update_fields=['property_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_property_property_id"),
    ]

    operations = [
        migrations.RunPython(generate_property_ids, reverse_code=migrations.RunPython.noop),
    ]
