# Generated by Django 4.2.15 on 2025-11-16 02:21

from django.db import migrations


def generate_property_ids(apps, schema_editor):
    """Generate property_id for all existing properties"""
    Property = apps.get_model("properties", "Property")

    for property_obj in Property.objects.filter(property_id=""):
        # Trigger save to generate property_id
        # Note: We need to call the model's save method directly
        property_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_property_property_id"),
    ]

    operations = [
        migrations.RunPython(generate_property_ids, reverse_code=migrations.RunPython.noop),
    ]
