# Generated by Django 4.2.15 on 2025-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0027_generate_property_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique property identifier with property name prefix",
                max_length=100,
                unique=True,  # Now add the unique constraint
            ),
        ),
    ]
