import './globals.css'; // Ensure this imports Tailwind's global styles
import Navbar from './components/static/Navbar';
import Footer from './components/static/Footer';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can leave <head> empty since metadata is managed by the `metadata` object */}
      </head>
      <body className="bg-background text-foregroun">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
