# Generated by Django 5.1.6 on 2025-02-19 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('LAND', 'Land')], max_length=20)),
                ('listing_type', models.CharField(choices=[('SALE', 'Sale'), ('RENT', 'Rent')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('listed_by', models.ForeignKey(limit_choices_to={'user_type__in': ['ADMIN', 'AGENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
