# Generated by Django 5.1.6 on 2025-03-05 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='property_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listed_by',
        ),
        migrations.AddField(
            model_name='property',
            name='rent_frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], help_text='Frequency of rent payment (applicable for rental listings)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rent price (applicable for rental listings)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PropertyFeatureAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=False)),
                ('listed_by', models.ForeignKey(limit_choices_to={'user_type__in': ['ADMIN', 'AGENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property Features & Amenities',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='features_amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.propertyfeatureamenity'),
        ),
    ]
