# Generated by Django 5.1.6 on 2025-03-05 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_title_property_property_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features_amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='listed_by',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type__in': ['ADMIN', 'AGENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyFeatureAmenity',
        ),
        migrations.AddField(
            model_name='property',
            name='features_amenities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
