# Generated by Django 5.1.6 on 2025-03-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_improve_features_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features_amenities',
        ),
    ]
