# Generated by Django 5.1.6 on 2025-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_property_video_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RENTED', 'Rented')], default='AVAILABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (applicable for sale listings)', max_digits=12, null=True),
        ),
    ]
