# Generated by Django 5.1.6 on 2025-05-11 17:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agent commission percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lister_type',
            field=models.CharField(choices=[('LANDLOARD', 'Landlord'), ('AGENT', 'Agent')], default='AGENT', help_text='Type of lister (landlord or agent)', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='qaba_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qaba fee percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('SELF_CONTAIN', 'Self Contain'), ('DUPLEX', 'Duplex'), ('SEMI_DETACHED', 'Semi Detached'), ('FULL_DETACHED', 'Full Detached'), ('ONE_BEDROOM_FLAT', 'One Bedroom Flat'), ('TWO_BEDROOM_FLAT', 'Two Bedroom Flat'), ('THREE_BEDROOM_FLAT', 'Three Bedroom Flat'), ('FOUR_BEDROOM_FLAT', 'Four Bedroom Flat'), ('WAREHOUSE', 'Warehouse'), ('EMPTY_LAND', 'Empty Land'), ('LAND_WITH_BUILDING', 'Land with Building')], max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DEED', 'Deed'), ('TITLE', 'Title Certificate'), ('PERMIT', 'Building Permit'), ('SURVEY', 'Survey Plan'), ('LAND_USE', 'Land Use Approval'), ('TAX', 'Tax Receipt'), ('FLOOR_PLAN', 'Floor Plan'), ('UTILITY', 'Utility Bills'), ('OTHER', 'Other Document')], default='OTHER', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(help_text='Upload a document for the property (PDF, DOC, etc.)', max_length=255, verbose_name='document')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the document has been verified by admin')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
