# Generated by Django 5.1.6 on 2025-07-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_city_property_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lister_type',
        ),
    ]
