# Generated by Django 5.1.6 on 2025-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_payment_type_transaction_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('purchase', 'Property Purchase'), ('rent', 'Property Rent')], default='rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
