# Generated by Django 5.1.6 on 2025-07-11 08:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_city_property_state'),
        ('transactions', '0003_alter_transaction_payment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_receipt',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload payment receipt for offline payments', max_length=255, null=True, verbose_name='payment_receipts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the offline payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='failed', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_9cef77_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['property_obj'], name='transaction_propert_4ac08a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method', 'status'], name='transaction_payment_a92a71_idx'),
        ),
    ]
