# Generated by Django 4.2.15 on 2025-10-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_alter_property_id"),
        ("transactions", "0004_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="property_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="properties.property",
            ),
        ),
    ]
