# Generated by Django 5.1.6 on 2025-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=150)),
                ("pay_range", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("requirement", models.TextField()),
            ],
        ),
    ]
