# Generated by Django 5.1.6 on 2025-09-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="applications", to="jobs.job")),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("year_of_exp", models.PositiveIntegerField()),
                ("degree", models.CharField(max_length=150)),
                ("bio", models.TextField()),
                ("cv", models.FileField(upload_to="job_applications/cv/")),
            ],
        ),
    ]
