# Generated by Django 5.1.6 on 2025-09-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="jobform",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
