# Generated by Django 5.1.6 on 2025-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_options_alter_jobform_options_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobform",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobform",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="jobform",
            name="referral",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
