# Generated by Django 5.1.6 on 2025-09-19 13:40

from django.db import migrations, models
from django.utils.text import slugify


def populate_job_slugs(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")

    for job in Job.objects.all():
        if job.slug:
            continue

        base_slug = slugify(job.title) or f"job-{job.pk}"
        slug = base_slug
        counter = 1

        existing = (
            Job.objects.filter(slug=slug)
            .exclude(pk=job.pk)
            .exists()
        )

        while existing:
            slug = f"{base_slug}-{counter}"
            counter += 1
            existing = (
                Job.objects.filter(slug=slug)
                .exclude(pk=job.pk)
                .exists()
            )

        job.slug = slug
        job.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobform_linkedin_url_jobform_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_job_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
