# Generated by Django 5.1.6 on 2025-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("FULLTIME", "Full-time"),
                    ("PARTTIME", "Part-time"),
                    ("INTERNSHIP", "Internship"),
                ],
                default="FULLTIME",
                max_length=15,
            ),
        ),
    ]
