# Generated by Django 5.1.6 on 2025-09-23 05:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobform',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv'),
        ),
    ]
