# Generated by Django 5.1.6 on 2025-03-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
    ]
