# Generated by Django 5.1.6 on 2025-03-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='specializations',
            new_name='_state',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='preferred_location',
            new_name='_state',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='budget_range',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
