# Generated by Django 5.1.6 on 2025-03-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_specializations_agentprofile__state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='_state',
            new_name='state',
        ),
    ]
