# Generated by Django 5.1.6 on 2025-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename__state_agentprofile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
