# Generated by Django 5.1.6 on 2025-07-11 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_user_type_landlordprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySurveyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(help_text='Reference to property listing', max_length=100)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin/agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'property_id'], name='users_prope_user_id_23b87e_idx'), models.Index(fields=['scheduled_date', 'scheduled_time'], name='users_prope_schedul_e2d6cb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('user', 'property_id'), name='unique_active_meeting_per_property')],
            },
        ),
    ]
