# Generated by Django 4.2.15 on 2025-10-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_email_verification_token_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_reset_token",
        ),
    ]
