name: CI/CD - Deploy to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Pre-deployment validation job
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/qaba-frontend/package-lock.json

      - name: Install Backend dependencies
        run: |
          cd Backend/qaba-api
          pip install -r requirements.txt

      - name: Run Backend tests
        run: |
          cd Backend/qaba-api
          pytest --maxfail=1 --disable-warnings -v || echo "::warning::Backend tests failed but continuing"

      - name: Backend linting
        run: |
          cd Backend/qaba-api
          pip install flake8 || true
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "::warning::Linting issues found"

      - name: Install Frontend dependencies
        run: |
          cd Frontend/qaba-frontend
          npm ci

      - name: Run Frontend linting
        run: |
          cd Frontend/qaba-frontend
          npm run lint || echo "::warning::Frontend linting issues found"

      - name: Build Frontend
        run: |
          cd Frontend/qaba-frontend
          npm run build

      - name: Verify Docker Compose file
        env:
          ENV_FILE: env.example
        run: docker compose -f docker-compose.yml config -q

  # Build and push Docker images to registry
  build-images:
    runs-on: ubuntu-latest
    needs: test-and-validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/backend:buildcache,mode=max

      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/frontend
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:buildcache,mode=max

  # Main deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build-images
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project files to VM
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.VM_SSH_KEY }}
            port: ${{ secrets.VM_SSH_PORT || 22 }}
            source: "./"
            target: ${{ secrets.VM_PROJECT_DIR }}
            overwrite: true
            strip_components: 0
            exclude: |
                .git/**
                **/.git/**
                .env
                node_modules/**
                **/node_modules/**
                .next/**
                **/.next/**
                Backend/qaba-api/media/**
                __pycache__/**
                **/__pycache__/**
                *.pyc
                .pytest_cache/**

      - name: Create backup and deploy
        id: deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: ${{ secrets.VM_PROJECT_DIR }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT || 22 }}
          envs: PROJECT_DIR,GITHUB_SHA,DOCKER_REGISTRY
          script: |
            set -euo pipefail

            # Ensure project dir exists
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"

            echo "📦 Creating backup of current deployment..."
            BACKUP_DIR="${PROJECT_DIR}_backup_$(date +%Y%m%d_%H%M%S)"

            # Backup current state if it exists
            if [ -f docker-compose.yml ]; then
              mkdir -p "$BACKUP_DIR"
              docker compose ps > "$BACKUP_DIR/containers_state.txt" || true
              cp docker-compose.yml "$BACKUP_DIR/" || true
              cp .env "$BACKUP_DIR/" || true
              echo "Backup created at: $BACKUP_DIR"
            fi

            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull latest images
            echo "🔄 Pulling latest Docker images..."
            docker pull ${DOCKER_REGISTRY}/backend:main-${GITHUB_SHA:0:7} || docker pull ${DOCKER_REGISTRY}/backend:latest
            docker pull ${DOCKER_REGISTRY}/frontend:main-${GITHUB_SHA:0:7} || docker pull ${DOCKER_REGISTRY}/frontend:latest

            # Update docker-compose to use registry images
            export BACKEND_IMAGE="${DOCKER_REGISTRY}/backend:main-${GITHUB_SHA:0:7}"
            export FRONTEND_IMAGE="${DOCKER_REGISTRY}/frontend:main-${GITHUB_SHA:0:7}"

            echo "🚀 Starting deployment..."
            # Deploy with zero-downtime using rolling update with pre-built images
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build --remove-orphans

            echo "⏳ Waiting for services to be ready..."
            sleep 10

      - name: Health check deployment
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: ${{ secrets.VM_PROJECT_DIR }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT || 22 }}
          envs: PROJECT_DIR
          script: |
            set -euo pipefail
            cd "$PROJECT_DIR"

            echo "🔍 Checking container health..."

            # Check if containers are running
            CONTAINERS=$(docker compose ps -q)
            if [ -z "$CONTAINERS" ]; then
              echo "❌ No containers are running!"
              exit 1
            fi

            # Check each service
            for service in backend frontend db; do
              if ! docker compose ps $service | grep -q "Up"; then
                echo "❌ Service $service is not running!"
                docker compose logs --tail=50 $service
                exit 1
              fi
            done

            # Health check endpoints
            echo "Testing backend health..."
            max_attempts=30
            attempt=0
            while [ $attempt -lt $max_attempts ]; do
              if curl -f http://localhost:8000/health 2>/dev/null || curl -f http://localhost:8000/ 2>/dev/null; then
                echo "✅ Backend is healthy"
                break
              fi
              attempt=$((attempt + 1))
              if [ $attempt -eq $max_attempts ]; then
                echo "❌ Backend health check failed after $max_attempts attempts"
                docker compose logs --tail=50 backend
                exit 1
              fi
              sleep 2
            done

            echo "Testing frontend health..."
            attempt=0
            while [ $attempt -lt $max_attempts ]; do
              if curl -f http://localhost:3000/ 2>/dev/null; then
                echo "✅ Frontend is healthy"
                break
              fi
              attempt=$((attempt + 1))
              if [ $attempt -eq $max_attempts ]; then
                echo "❌ Frontend health check failed after $max_attempts attempts"
                docker compose logs --tail=50 frontend
                exit 1
              fi
              sleep 2
            done

            echo "✅ All services are healthy!"
            docker compose ps

      - name: Cleanup old resources
        if: success()
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: ${{ secrets.VM_PROJECT_DIR }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT || 22 }}
          envs: PROJECT_DIR
          script: |
            cd "$PROJECT_DIR"

            echo "🧹 Cleaning up old Docker resources..."
            docker system prune -f --volumes || true

            # Keep only last 1 backup
            echo "🧹 Cleaning old backups (keeping last 1)..."
            ls -dt ${PROJECT_DIR}_backup_* 2>/dev/null | tail -n +2 | xargs rm -rf || true

      - name: Rollback on failure
        if: failure()
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: ${{ secrets.VM_PROJECT_DIR }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT || 22 }}
          envs: PROJECT_DIR
          script: |
            set -euo pipefail
            cd "$PROJECT_DIR"

            echo "⚠️ Deployment failed! Attempting rollback..."

            # Find most recent backup
            LATEST_BACKUP=$(ls -dt ${PROJECT_DIR}_backup_* 2>/dev/null | head -1)

            if [ -n "$LATEST_BACKUP" ] && [ -d "$LATEST_BACKUP" ]; then
              echo "Rolling back to: $LATEST_BACKUP"

              # Restore backup files
              cp "$LATEST_BACKUP/docker-compose.yml" . || true
              cp "$LATEST_BACKUP/.env" . || true

              # Restart with previous configuration
              docker compose down
              docker compose up -d

              echo "✅ Rollback completed"
            else
              echo "❌ No backup found for rollback"
              exit 1
            fi